// Auto-generated. Do not edit!

// (in-package qarm_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let QArmActionFeedback = require('./QArmActionFeedback.js');

//-----------------------------------------------------------

class moveQArmFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.qarm_action_feedback = null;
    }
    else {
      if (initObj.hasOwnProperty('qarm_action_feedback')) {
        this.qarm_action_feedback = initObj.qarm_action_feedback
      }
      else {
        this.qarm_action_feedback = new QArmActionFeedback();
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type moveQArmFeedback
    // Serialize message field [qarm_action_feedback]
    bufferOffset = QArmActionFeedback.serialize(obj.qarm_action_feedback, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type moveQArmFeedback
    let len;
    let data = new moveQArmFeedback(null);
    // Deserialize message field [qarm_action_feedback]
    data.qarm_action_feedback = QArmActionFeedback.deserialize(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += QArmActionFeedback.getMessageSize(object.qarm_action_feedback);
    return length;
  }

  static datatype() {
    // Returns string type for a message object
    return 'qarm_msgs/moveQArmFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '7e69a7e80ecd0036ac9e7999a607b129';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # feedback
    qarm_msgs/QArmActionFeedback qarm_action_feedback
    
    ================================================================================
    MSG: qarm_msgs/QArmActionFeedback
    Header header
    
    actionlib_msgs/GoalID goal_id
    qarm_msgs/AllJointState ajs
    ================================================================================
    MSG: std_msgs/Header
    # Standard metadata for higher-level stamped data types.
    # This is generally used to communicate timestamped data 
    # in a particular coordinate frame.
    # 
    # sequence ID: consecutively increasing ID 
    uint32 seq
    #Two-integer timestamp that is expressed as:
    # * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
    # * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
    # time-handling sugar is provided by the client library
    time stamp
    #Frame this data is associated with
    string frame_id
    
    ================================================================================
    MSG: actionlib_msgs/GoalID
    # The stamp should store the time at which this goal was requested.
    # It is used by an action server when it tries to preempt all
    # goals that were requested before a certain time
    time stamp
    
    # The id provides a way to associate feedback and
    # result message with specific goal requests. The id
    # specified must be unique.
    string id
    
    
    ================================================================================
    MSG: qarm_msgs/AllJointState
    
    std_msgs/Header header
    
    # Name
    string joint_names
    
    # JointCurrent
    float64[] joint_currents
    
    # JointPosition (rad)
    float64[] joint_positions
    
    # JointSpeed (rad/s)
    float64[] joint_speeds
    
    # JointPWM
    float64[] joint_pwms
    
    # JointTemperature
    float64[] joint_temperatures
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new moveQArmFeedback(null);
    if (msg.qarm_action_feedback !== undefined) {
      resolved.qarm_action_feedback = QArmActionFeedback.Resolve(msg.qarm_action_feedback)
    }
    else {
      resolved.qarm_action_feedback = new QArmActionFeedback()
    }

    return resolved;
    }
};

module.exports = moveQArmFeedback;
