// Generated by gencpp from file qarm_msgs/moveQArmActionGoal.msg
// DO NOT EDIT!


#ifndef QARM_MSGS_MESSAGE_MOVEQARMACTIONGOAL_H
#define QARM_MSGS_MESSAGE_MOVEQARMACTIONGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <actionlib_msgs/GoalID.h>
#include <qarm_msgs/moveQArmGoal.h>

namespace qarm_msgs
{
template <class ContainerAllocator>
struct moveQArmActionGoal_
{
  typedef moveQArmActionGoal_<ContainerAllocator> Type;

  moveQArmActionGoal_()
    : header()
    , goal_id()
    , goal()  {
    }
  moveQArmActionGoal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , goal_id(_alloc)
    , goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
  _goal_id_type goal_id;

   typedef  ::qarm_msgs::moveQArmGoal_<ContainerAllocator>  _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::qarm_msgs::moveQArmActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::qarm_msgs::moveQArmActionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct moveQArmActionGoal_

typedef ::qarm_msgs::moveQArmActionGoal_<std::allocator<void> > moveQArmActionGoal;

typedef boost::shared_ptr< ::qarm_msgs::moveQArmActionGoal > moveQArmActionGoalPtr;
typedef boost::shared_ptr< ::qarm_msgs::moveQArmActionGoal const> moveQArmActionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::qarm_msgs::moveQArmActionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::qarm_msgs::moveQArmActionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::qarm_msgs::moveQArmActionGoal_<ContainerAllocator1> & lhs, const ::qarm_msgs::moveQArmActionGoal_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.goal_id == rhs.goal_id &&
    lhs.goal == rhs.goal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::qarm_msgs::moveQArmActionGoal_<ContainerAllocator1> & lhs, const ::qarm_msgs::moveQArmActionGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace qarm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::qarm_msgs::moveQArmActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::qarm_msgs::moveQArmActionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::qarm_msgs::moveQArmActionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::qarm_msgs::moveQArmActionGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qarm_msgs::moveQArmActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qarm_msgs::moveQArmActionGoal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::qarm_msgs::moveQArmActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7fe83e3898191874e42e747d3bcb4acd";
  }

  static const char* value(const ::qarm_msgs::moveQArmActionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7fe83e3898191874ULL;
  static const uint64_t static_value2 = 0xe42e747d3bcb4acdULL;
};

template<class ContainerAllocator>
struct DataType< ::qarm_msgs::moveQArmActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "qarm_msgs/moveQArmActionGoal";
  }

  static const char* value(const ::qarm_msgs::moveQArmActionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::qarm_msgs::moveQArmActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalID goal_id\n"
"moveQArmGoal goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: qarm_msgs/moveQArmGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# goal\n"
"qarm_msgs/QArmActionGoal qarm_action_goal\n"
"\n"
"================================================================================\n"
"MSG: qarm_msgs/QArmActionGoal\n"
"Header header\n"
"\n"
"actionlib_msgs/GoalID goal_id\n"
"float64[] task_space_position_and_gripper\n"
;
  }

  static const char* value(const ::qarm_msgs::moveQArmActionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::qarm_msgs::moveQArmActionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.goal_id);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct moveQArmActionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::qarm_msgs::moveQArmActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::qarm_msgs::moveQArmActionGoal_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "goal_id: ";
    s << std::endl;
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::qarm_msgs::moveQArmGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // QARM_MSGS_MESSAGE_MOVEQARMACTIONGOAL_H
