// Generated by gencpp from file qarm_msgs/moveQArmAction.msg
// DO NOT EDIT!


#ifndef QARM_MSGS_MESSAGE_MOVEQARMACTION_H
#define QARM_MSGS_MESSAGE_MOVEQARMACTION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <qarm_msgs/moveQArmActionGoal.h>
#include <qarm_msgs/moveQArmActionResult.h>
#include <qarm_msgs/moveQArmActionFeedback.h>

namespace qarm_msgs
{
template <class ContainerAllocator>
struct moveQArmAction_
{
  typedef moveQArmAction_<ContainerAllocator> Type;

  moveQArmAction_()
    : action_goal()
    , action_result()
    , action_feedback()  {
    }
  moveQArmAction_(const ContainerAllocator& _alloc)
    : action_goal(_alloc)
    , action_result(_alloc)
    , action_feedback(_alloc)  {
  (void)_alloc;
    }



   typedef  ::qarm_msgs::moveQArmActionGoal_<ContainerAllocator>  _action_goal_type;
  _action_goal_type action_goal;

   typedef  ::qarm_msgs::moveQArmActionResult_<ContainerAllocator>  _action_result_type;
  _action_result_type action_result;

   typedef  ::qarm_msgs::moveQArmActionFeedback_<ContainerAllocator>  _action_feedback_type;
  _action_feedback_type action_feedback;





  typedef boost::shared_ptr< ::qarm_msgs::moveQArmAction_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::qarm_msgs::moveQArmAction_<ContainerAllocator> const> ConstPtr;

}; // struct moveQArmAction_

typedef ::qarm_msgs::moveQArmAction_<std::allocator<void> > moveQArmAction;

typedef boost::shared_ptr< ::qarm_msgs::moveQArmAction > moveQArmActionPtr;
typedef boost::shared_ptr< ::qarm_msgs::moveQArmAction const> moveQArmActionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::qarm_msgs::moveQArmAction_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::qarm_msgs::moveQArmAction_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::qarm_msgs::moveQArmAction_<ContainerAllocator1> & lhs, const ::qarm_msgs::moveQArmAction_<ContainerAllocator2> & rhs)
{
  return lhs.action_goal == rhs.action_goal &&
    lhs.action_result == rhs.action_result &&
    lhs.action_feedback == rhs.action_feedback;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::qarm_msgs::moveQArmAction_<ContainerAllocator1> & lhs, const ::qarm_msgs::moveQArmAction_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace qarm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::qarm_msgs::moveQArmAction_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::qarm_msgs::moveQArmAction_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::qarm_msgs::moveQArmAction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::qarm_msgs::moveQArmAction_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qarm_msgs::moveQArmAction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qarm_msgs::moveQArmAction_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::qarm_msgs::moveQArmAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fbb61b6b6cc13579b1ad461893060728";
  }

  static const char* value(const ::qarm_msgs::moveQArmAction_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfbb61b6b6cc13579ULL;
  static const uint64_t static_value2 = 0xb1ad461893060728ULL;
};

template<class ContainerAllocator>
struct DataType< ::qarm_msgs::moveQArmAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "qarm_msgs/moveQArmAction";
  }

  static const char* value(const ::qarm_msgs::moveQArmAction_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::qarm_msgs::moveQArmAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"moveQArmActionGoal action_goal\n"
"moveQArmActionResult action_result\n"
"moveQArmActionFeedback action_feedback\n"
"\n"
"================================================================================\n"
"MSG: qarm_msgs/moveQArmActionGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalID goal_id\n"
"moveQArmGoal goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: qarm_msgs/moveQArmGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# goal\n"
"qarm_msgs/QArmActionGoal qarm_action_goal\n"
"\n"
"================================================================================\n"
"MSG: qarm_msgs/QArmActionGoal\n"
"Header header\n"
"\n"
"actionlib_msgs/GoalID goal_id\n"
"float64[] task_space_position_and_gripper\n"
"================================================================================\n"
"MSG: qarm_msgs/moveQArmActionResult\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalStatus status\n"
"moveQArmResult result\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalStatus\n"
"GoalID goal_id\n"
"uint8 status\n"
"uint8 PENDING         = 0   # The goal has yet to be processed by the action server\n"
"uint8 ACTIVE          = 1   # The goal is currently being processed by the action server\n"
"uint8 PREEMPTED       = 2   # The goal received a cancel request after it started executing\n"
"                            #   and has since completed its execution (Terminal State)\n"
"uint8 SUCCEEDED       = 3   # The goal was achieved successfully by the action server (Terminal State)\n"
"uint8 ABORTED         = 4   # The goal was aborted during execution by the action server due\n"
"                            #    to some failure (Terminal State)\n"
"uint8 REJECTED        = 5   # The goal was rejected by the action server without being processed,\n"
"                            #    because the goal was unattainable or invalid (Terminal State)\n"
"uint8 PREEMPTING      = 6   # The goal received a cancel request after it started executing\n"
"                            #    and has not yet completed execution\n"
"uint8 RECALLING       = 7   # The goal received a cancel request before it started executing,\n"
"                            #    but the action server has not yet confirmed that the goal is canceled\n"
"uint8 RECALLED        = 8   # The goal received a cancel request before it started executing\n"
"                            #    and was successfully cancelled (Terminal State)\n"
"uint8 LOST            = 9   # An action client can determine that a goal is LOST. This should not be\n"
"                            #    sent over the wire by an action server\n"
"\n"
"#Allow for the user to associate a string with GoalStatus for debugging\n"
"string text\n"
"\n"
"\n"
"================================================================================\n"
"MSG: qarm_msgs/moveQArmResult\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# result\n"
"qarm_msgs/QArmActionResult qarm_action_result\n"
"\n"
"================================================================================\n"
"MSG: qarm_msgs/QArmActionResult\n"
"Header header\n"
"\n"
"actionlib_msgs/GoalStatus status\n"
"# int32 ready_for_next_goal\n"
"string result\n"
"================================================================================\n"
"MSG: qarm_msgs/moveQArmActionFeedback\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalStatus status\n"
"moveQArmFeedback feedback\n"
"\n"
"================================================================================\n"
"MSG: qarm_msgs/moveQArmFeedback\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# feedback\n"
"qarm_msgs/QArmActionFeedback qarm_action_feedback\n"
"\n"
"================================================================================\n"
"MSG: qarm_msgs/QArmActionFeedback\n"
"Header header\n"
"\n"
"actionlib_msgs/GoalID goal_id\n"
"qarm_msgs/AllJointState ajs\n"
"================================================================================\n"
"MSG: qarm_msgs/AllJointState\n"
"\n"
"std_msgs/Header header\n"
"\n"
"# Name\n"
"string joint_names\n"
"\n"
"# JointCurrent\n"
"float64[] joint_currents\n"
"\n"
"# JointPosition (rad)\n"
"float64[] joint_positions\n"
"\n"
"# JointSpeed (rad/s)\n"
"float64[] joint_speeds\n"
"\n"
"# JointPWM\n"
"float64[] joint_pwms\n"
"\n"
"# JointTemperature\n"
"float64[] joint_temperatures\n"
;
  }

  static const char* value(const ::qarm_msgs::moveQArmAction_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::qarm_msgs::moveQArmAction_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.action_goal);
      stream.next(m.action_result);
      stream.next(m.action_feedback);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct moveQArmAction_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::qarm_msgs::moveQArmAction_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::qarm_msgs::moveQArmAction_<ContainerAllocator>& v)
  {
    s << indent << "action_goal: ";
    s << std::endl;
    Printer< ::qarm_msgs::moveQArmActionGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.action_goal);
    s << indent << "action_result: ";
    s << std::endl;
    Printer< ::qarm_msgs::moveQArmActionResult_<ContainerAllocator> >::stream(s, indent + "  ", v.action_result);
    s << indent << "action_feedback: ";
    s << std::endl;
    Printer< ::qarm_msgs::moveQArmActionFeedback_<ContainerAllocator> >::stream(s, indent + "  ", v.action_feedback);
  }
};

} // namespace message_operations
} // namespace ros

#endif // QARM_MSGS_MESSAGE_MOVEQARMACTION_H
