// Generated by gencpp from file qarm_msgs/moveQArmGoal.msg
// DO NOT EDIT!


#ifndef QARM_MSGS_MESSAGE_MOVEQARMGOAL_H
#define QARM_MSGS_MESSAGE_MOVEQARMGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <qarm_msgs/QArmActionGoal.h>

namespace qarm_msgs
{
template <class ContainerAllocator>
struct moveQArmGoal_
{
  typedef moveQArmGoal_<ContainerAllocator> Type;

  moveQArmGoal_()
    : qarm_action_goal()  {
    }
  moveQArmGoal_(const ContainerAllocator& _alloc)
    : qarm_action_goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::qarm_msgs::QArmActionGoal_<ContainerAllocator>  _qarm_action_goal_type;
  _qarm_action_goal_type qarm_action_goal;





  typedef boost::shared_ptr< ::qarm_msgs::moveQArmGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::qarm_msgs::moveQArmGoal_<ContainerAllocator> const> ConstPtr;

}; // struct moveQArmGoal_

typedef ::qarm_msgs::moveQArmGoal_<std::allocator<void> > moveQArmGoal;

typedef boost::shared_ptr< ::qarm_msgs::moveQArmGoal > moveQArmGoalPtr;
typedef boost::shared_ptr< ::qarm_msgs::moveQArmGoal const> moveQArmGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::qarm_msgs::moveQArmGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::qarm_msgs::moveQArmGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::qarm_msgs::moveQArmGoal_<ContainerAllocator1> & lhs, const ::qarm_msgs::moveQArmGoal_<ContainerAllocator2> & rhs)
{
  return lhs.qarm_action_goal == rhs.qarm_action_goal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::qarm_msgs::moveQArmGoal_<ContainerAllocator1> & lhs, const ::qarm_msgs::moveQArmGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace qarm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::qarm_msgs::moveQArmGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::qarm_msgs::moveQArmGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::qarm_msgs::moveQArmGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::qarm_msgs::moveQArmGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qarm_msgs::moveQArmGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qarm_msgs::moveQArmGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::qarm_msgs::moveQArmGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e20b3cc33cfad8c835bf4d09f0f0006e";
  }

  static const char* value(const ::qarm_msgs::moveQArmGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe20b3cc33cfad8c8ULL;
  static const uint64_t static_value2 = 0x35bf4d09f0f0006eULL;
};

template<class ContainerAllocator>
struct DataType< ::qarm_msgs::moveQArmGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "qarm_msgs/moveQArmGoal";
  }

  static const char* value(const ::qarm_msgs::moveQArmGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::qarm_msgs::moveQArmGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# goal\n"
"qarm_msgs/QArmActionGoal qarm_action_goal\n"
"\n"
"================================================================================\n"
"MSG: qarm_msgs/QArmActionGoal\n"
"Header header\n"
"\n"
"actionlib_msgs/GoalID goal_id\n"
"float64[] task_space_position_and_gripper\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
;
  }

  static const char* value(const ::qarm_msgs::moveQArmGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::qarm_msgs::moveQArmGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.qarm_action_goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct moveQArmGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::qarm_msgs::moveQArmGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::qarm_msgs::moveQArmGoal_<ContainerAllocator>& v)
  {
    s << indent << "qarm_action_goal: ";
    s << std::endl;
    Printer< ::qarm_msgs::QArmActionGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.qarm_action_goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // QARM_MSGS_MESSAGE_MOVEQARMGOAL_H
