// Generated by gencpp from file qarm_msgs/moveQArmResult.msg
// DO NOT EDIT!


#ifndef QARM_MSGS_MESSAGE_MOVEQARMRESULT_H
#define QARM_MSGS_MESSAGE_MOVEQARMRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <qarm_msgs/QArmActionResult.h>

namespace qarm_msgs
{
template <class ContainerAllocator>
struct moveQArmResult_
{
  typedef moveQArmResult_<ContainerAllocator> Type;

  moveQArmResult_()
    : qarm_action_result()  {
    }
  moveQArmResult_(const ContainerAllocator& _alloc)
    : qarm_action_result(_alloc)  {
  (void)_alloc;
    }



   typedef  ::qarm_msgs::QArmActionResult_<ContainerAllocator>  _qarm_action_result_type;
  _qarm_action_result_type qarm_action_result;





  typedef boost::shared_ptr< ::qarm_msgs::moveQArmResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::qarm_msgs::moveQArmResult_<ContainerAllocator> const> ConstPtr;

}; // struct moveQArmResult_

typedef ::qarm_msgs::moveQArmResult_<std::allocator<void> > moveQArmResult;

typedef boost::shared_ptr< ::qarm_msgs::moveQArmResult > moveQArmResultPtr;
typedef boost::shared_ptr< ::qarm_msgs::moveQArmResult const> moveQArmResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::qarm_msgs::moveQArmResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::qarm_msgs::moveQArmResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::qarm_msgs::moveQArmResult_<ContainerAllocator1> & lhs, const ::qarm_msgs::moveQArmResult_<ContainerAllocator2> & rhs)
{
  return lhs.qarm_action_result == rhs.qarm_action_result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::qarm_msgs::moveQArmResult_<ContainerAllocator1> & lhs, const ::qarm_msgs::moveQArmResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace qarm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::qarm_msgs::moveQArmResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::qarm_msgs::moveQArmResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::qarm_msgs::moveQArmResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::qarm_msgs::moveQArmResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qarm_msgs::moveQArmResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qarm_msgs::moveQArmResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::qarm_msgs::moveQArmResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4cd8ec53d650973e9e7c5da9f8d65ecb";
  }

  static const char* value(const ::qarm_msgs::moveQArmResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4cd8ec53d650973eULL;
  static const uint64_t static_value2 = 0x9e7c5da9f8d65ecbULL;
};

template<class ContainerAllocator>
struct DataType< ::qarm_msgs::moveQArmResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "qarm_msgs/moveQArmResult";
  }

  static const char* value(const ::qarm_msgs::moveQArmResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::qarm_msgs::moveQArmResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# result\n"
"qarm_msgs/QArmActionResult qarm_action_result\n"
"\n"
"================================================================================\n"
"MSG: qarm_msgs/QArmActionResult\n"
"Header header\n"
"\n"
"actionlib_msgs/GoalStatus status\n"
"# int32 ready_for_next_goal\n"
"string result\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalStatus\n"
"GoalID goal_id\n"
"uint8 status\n"
"uint8 PENDING         = 0   # The goal has yet to be processed by the action server\n"
"uint8 ACTIVE          = 1   # The goal is currently being processed by the action server\n"
"uint8 PREEMPTED       = 2   # The goal received a cancel request after it started executing\n"
"                            #   and has since completed its execution (Terminal State)\n"
"uint8 SUCCEEDED       = 3   # The goal was achieved successfully by the action server (Terminal State)\n"
"uint8 ABORTED         = 4   # The goal was aborted during execution by the action server due\n"
"                            #    to some failure (Terminal State)\n"
"uint8 REJECTED        = 5   # The goal was rejected by the action server without being processed,\n"
"                            #    because the goal was unattainable or invalid (Terminal State)\n"
"uint8 PREEMPTING      = 6   # The goal received a cancel request after it started executing\n"
"                            #    and has not yet completed execution\n"
"uint8 RECALLING       = 7   # The goal received a cancel request before it started executing,\n"
"                            #    but the action server has not yet confirmed that the goal is canceled\n"
"uint8 RECALLED        = 8   # The goal received a cancel request before it started executing\n"
"                            #    and was successfully cancelled (Terminal State)\n"
"uint8 LOST            = 9   # An action client can determine that a goal is LOST. This should not be\n"
"                            #    sent over the wire by an action server\n"
"\n"
"#Allow for the user to associate a string with GoalStatus for debugging\n"
"string text\n"
"\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
;
  }

  static const char* value(const ::qarm_msgs::moveQArmResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::qarm_msgs::moveQArmResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.qarm_action_result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct moveQArmResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::qarm_msgs::moveQArmResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::qarm_msgs::moveQArmResult_<ContainerAllocator>& v)
  {
    s << indent << "qarm_action_result: ";
    s << std::endl;
    Printer< ::qarm_msgs::QArmActionResult_<ContainerAllocator> >::stream(s, indent + "  ", v.qarm_action_result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // QARM_MSGS_MESSAGE_MOVEQARMRESULT_H
