; Auto-generated. Do not edit!


(cl:in-package qarm_msgs-msg)


;//! \htmlinclude moveQArmGoal.msg.html

(cl:defclass <moveQArmGoal> (roslisp-msg-protocol:ros-message)
  ((qarm_action_goal
    :reader qarm_action_goal
    :initarg :qarm_action_goal
    :type qarm_msgs-msg:QArmActionGoal
    :initform (cl:make-instance 'qarm_msgs-msg:QArmActionGoal)))
)

(cl:defclass moveQArmGoal (<moveQArmGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <moveQArmGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'moveQArmGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name qarm_msgs-msg:<moveQArmGoal> is deprecated: use qarm_msgs-msg:moveQArmGoal instead.")))

(cl:ensure-generic-function 'qarm_action_goal-val :lambda-list '(m))
(cl:defmethod qarm_action_goal-val ((m <moveQArmGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader qarm_msgs-msg:qarm_action_goal-val is deprecated.  Use qarm_msgs-msg:qarm_action_goal instead.")
  (qarm_action_goal m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <moveQArmGoal>) ostream)
  "Serializes a message object of type '<moveQArmGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'qarm_action_goal) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <moveQArmGoal>) istream)
  "Deserializes a message object of type '<moveQArmGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'qarm_action_goal) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<moveQArmGoal>)))
  "Returns string type for a message object of type '<moveQArmGoal>"
  "qarm_msgs/moveQArmGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'moveQArmGoal)))
  "Returns string type for a message object of type 'moveQArmGoal"
  "qarm_msgs/moveQArmGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<moveQArmGoal>)))
  "Returns md5sum for a message object of type '<moveQArmGoal>"
  "e20b3cc33cfad8c835bf4d09f0f0006e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'moveQArmGoal)))
  "Returns md5sum for a message object of type 'moveQArmGoal"
  "e20b3cc33cfad8c835bf4d09f0f0006e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<moveQArmGoal>)))
  "Returns full string definition for message of type '<moveQArmGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# goal~%qarm_msgs/QArmActionGoal qarm_action_goal~%~%================================================================================~%MSG: qarm_msgs/QArmActionGoal~%Header header~%~%actionlib_msgs/GoalID goal_id~%float64[] task_space_position_and_gripper~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'moveQArmGoal)))
  "Returns full string definition for message of type 'moveQArmGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# goal~%qarm_msgs/QArmActionGoal qarm_action_goal~%~%================================================================================~%MSG: qarm_msgs/QArmActionGoal~%Header header~%~%actionlib_msgs/GoalID goal_id~%float64[] task_space_position_and_gripper~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <moveQArmGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'qarm_action_goal))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <moveQArmGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'moveQArmGoal
    (cl:cons ':qarm_action_goal (qarm_action_goal msg))
))
