; Auto-generated. Do not edit!


(cl:in-package qarm_msgs-msg)


;//! \htmlinclude moveQArmFeedback.msg.html

(cl:defclass <moveQArmFeedback> (roslisp-msg-protocol:ros-message)
  ((qarm_action_feedback
    :reader qarm_action_feedback
    :initarg :qarm_action_feedback
    :type qarm_msgs-msg:QArmActionFeedback
    :initform (cl:make-instance 'qarm_msgs-msg:QArmActionFeedback)))
)

(cl:defclass moveQArmFeedback (<moveQArmFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <moveQArmFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'moveQArmFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name qarm_msgs-msg:<moveQArmFeedback> is deprecated: use qarm_msgs-msg:moveQArmFeedback instead.")))

(cl:ensure-generic-function 'qarm_action_feedback-val :lambda-list '(m))
(cl:defmethod qarm_action_feedback-val ((m <moveQArmFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader qarm_msgs-msg:qarm_action_feedback-val is deprecated.  Use qarm_msgs-msg:qarm_action_feedback instead.")
  (qarm_action_feedback m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <moveQArmFeedback>) ostream)
  "Serializes a message object of type '<moveQArmFeedback>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'qarm_action_feedback) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <moveQArmFeedback>) istream)
  "Deserializes a message object of type '<moveQArmFeedback>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'qarm_action_feedback) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<moveQArmFeedback>)))
  "Returns string type for a message object of type '<moveQArmFeedback>"
  "qarm_msgs/moveQArmFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'moveQArmFeedback)))
  "Returns string type for a message object of type 'moveQArmFeedback"
  "qarm_msgs/moveQArmFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<moveQArmFeedback>)))
  "Returns md5sum for a message object of type '<moveQArmFeedback>"
  "7e69a7e80ecd0036ac9e7999a607b129")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'moveQArmFeedback)))
  "Returns md5sum for a message object of type 'moveQArmFeedback"
  "7e69a7e80ecd0036ac9e7999a607b129")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<moveQArmFeedback>)))
  "Returns full string definition for message of type '<moveQArmFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# feedback~%qarm_msgs/QArmActionFeedback qarm_action_feedback~%~%================================================================================~%MSG: qarm_msgs/QArmActionFeedback~%Header header~%~%actionlib_msgs/GoalID goal_id~%qarm_msgs/AllJointState ajs~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: qarm_msgs/AllJointState~%~%std_msgs/Header header~%~%# Name~%string joint_names~%~%# JointCurrent~%float64[] joint_currents~%~%# JointPosition (rad)~%float64[] joint_positions~%~%# JointSpeed (rad/s)~%float64[] joint_speeds~%~%# JointPWM~%float64[] joint_pwms~%~%# JointTemperature~%float64[] joint_temperatures~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'moveQArmFeedback)))
  "Returns full string definition for message of type 'moveQArmFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# feedback~%qarm_msgs/QArmActionFeedback qarm_action_feedback~%~%================================================================================~%MSG: qarm_msgs/QArmActionFeedback~%Header header~%~%actionlib_msgs/GoalID goal_id~%qarm_msgs/AllJointState ajs~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: qarm_msgs/AllJointState~%~%std_msgs/Header header~%~%# Name~%string joint_names~%~%# JointCurrent~%float64[] joint_currents~%~%# JointPosition (rad)~%float64[] joint_positions~%~%# JointSpeed (rad/s)~%float64[] joint_speeds~%~%# JointPWM~%float64[] joint_pwms~%~%# JointTemperature~%float64[] joint_temperatures~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <moveQArmFeedback>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'qarm_action_feedback))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <moveQArmFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'moveQArmFeedback
    (cl:cons ':qarm_action_feedback (qarm_action_feedback msg))
))
